services:

  spring:
    image: pinhouse/prod-server:latest
    container_name: pinhouse-app
    ports:
      - "8080:8080"
    volumes:
      # 서버의 설정파일 폴더를 컨테이너 내부로 연결
      - /home/ubuntu/app/config:/app/config
    environment:
      # Spring에게 외부 파일을 읽으라고 명령 (이게 핵심입니다)
      - SPRING_CONFIG_LOCATION=optional:classpath:/,file:/app/config/application-prod.yml,file:/app/config/application-oauth2-prod.yml
    networks:
      - backend-bridge

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - backend-bridge

networks:
  backend-bridge:
    driver: bridge
